using ClinicManagement.Application.Common.Interfaces;
using ClinicManagement.Application.Common.Models;
using ClinicManagement.Domain.Common.Constants;
using ClinicManagement.Domain.Common.Interfaces;
using ClinicManagement.Domain.Entities;
using FluentValidation;
using MediatR;
using Microsoft.EntityFrameworkCore;

namespace ClinicManagement.Application.Features.MedicalSupplies.Commands.CreateMedicalSupply;

public record CreateMedicalSupplyCommand : IRequest<Result<Guid>>
{
    public Guid ClinicBranchId { get; init; }
    public string Name { get; init; } = null!;
    public decimal UnitPrice { get; init; }
    public int QuantityInStock { get; init; }
    public int MinimumStockLevel { get; init; } = 10;
}


public class CreateMedicalSupplyCommandHandler : IRequestHandler<CreateMedicalSupplyCommand, Result<Guid>>
{
    private readonly IUnitOfWork _unitOfWork;

    public CreateMedicalSupplyCommandHandler(IUnitOfWork unitOfWork)
    {
        _unitOfWork = unitOfWork;
    }

    public async Task<Result<Guid>> Handle(CreateMedicalSupplyCommand request, CancellationToken cancellationToken)
    {
        // Check if clinic branch exists
        var clinicBranchExists = await _unitOfWork.Repository<ClinicBranch>()
            .AnyAsync(cb => cb.Id == request.ClinicBranchId, cancellationToken);
        
        if (!clinicBranchExists)
        {
            return Result<Guid>.FailSystem("NOT_FOUND", "Clinic branch not found");
        }

        // Check if medical supply with same name already exists in this clinic branch
        var existingSupply = await _unitOfWork.MedicalSupplies
            .GetByNameAndClinicBranchAsync(request.Name, request.ClinicBranchId, cancellationToken);
        
        if (existingSupply != null)
        {
            return Result<Guid>.FailValidation("name", "A medical supply with this name already exists in this clinic branch");
        }

        var supply = new MedicalSupply
        {
            // ID will be generated by database
            ClinicBranchId = request.ClinicBranchId,
            Name = request.Name,
            UnitPrice = request.UnitPrice,
            QuantityInStock = request.QuantityInStock,
            MinimumStockLevel = request.MinimumStockLevel
        };

        await _unitOfWork.MedicalSupplies.AddAsync(supply, cancellationToken);
        await _unitOfWork.SaveChangesAsync(cancellationToken);

        return Result<Guid>.Ok(supply.Id);
    }
}