using ClinicManagement.Domain.Common.Constants;
using ClinicManagement.Application.Common.Interfaces;
using ClinicManagement.Application.Common.Models;
using ClinicManagement.Domain.Common.Interfaces;
using ClinicManagement.Domain.Entities;
using MediatR;

namespace ClinicManagement.Application.Features.MedicalSupplies.Commands.CreateMedicalSupply;

public class CreateMedicalSupplyCommandHandler : IRequestHandler<CreateMedicalSupplyCommand, Result<Guid>>
{
    private readonly IUnitOfWork _unitOfWork;

    public CreateMedicalSupplyCommandHandler(IUnitOfWork unitOfWork)
    {
        _unitOfWork = unitOfWork;
    }

    public async Task<Result<Guid>> Handle(CreateMedicalSupplyCommand request, CancellationToken cancellationToken)
    {
        // Check if clinic branch exists
        var clinicBranchExists = await _unitOfWork.ClinicBranches.ExistsAsync(request.ClinicBranchId, cancellationToken);
        if (!clinicBranchExists)
        {
            return Result<Guid>.Fail(MessageCodes.Common.CLINIC_BRANCH_NOT_FOUND);
        }

        // Check if medical supply with same name already exists in this clinic branch
        var existingSupply = await _unitOfWork.MedicalSupplies.GetByNameAndClinicBranchAsync(request.Name, request.ClinicBranchId, cancellationToken);
        if (existingSupply != null)
        {
            return Result<Guid>.FailField("name", MessageCodes.MedicalSupply.ALREADY_EXISTS);
        }

        var supply = new MedicalSupply
        {
            // ID will be generated by database
            ClinicBranchId = request.ClinicBranchId,
            Name = request.Name,
            UnitPrice = request.UnitPrice,
            QuantityInStock = request.QuantityInStock,
            MinimumStockLevel = request.MinimumStockLevel
        };

        await _unitOfWork.MedicalSupplies.AddAsync(supply, cancellationToken);
        await _unitOfWork.SaveChangesAsync(cancellationToken);

        return Result<Guid>.Ok(supply.Id);
    }
}
