using ClinicManagement.Application.Common.Interfaces;
using ClinicManagement.Application.Common.Models;
using ClinicManagement.Domain.Common.Constants;
using ClinicManagement.Domain.Entities;
using FluentValidation;
using MediatR;
using Microsoft.EntityFrameworkCore;

namespace ClinicManagement.Application.Features.MedicalSupplies.Commands.CreateMedicalSupply;

public record CreateMedicalSupplyCommand : IRequest<Result<Guid>>
{
    public Guid ClinicBranchId { get; init; }
    public string Name { get; init; } = null!;
    public decimal UnitPrice { get; init; }
    public int QuantityInStock { get; init; }
    public int MinimumStockLevel { get; init; } = 10;
}


public class CreateMedicalSupplyCommandHandler : IRequestHandler<CreateMedicalSupplyCommand, Result<Guid>>
{
    private readonly IApplicationDbContext _context;

    public CreateMedicalSupplyCommandHandler(IApplicationDbContext context)
    {
        _context = context;
    }

    public async Task<Result<Guid>> Handle(CreateMedicalSupplyCommand request, CancellationToken cancellationToken)
    {
        // Check if clinic branch exists
        var clinicBranchExists = await _context.ClinicBranches
            .AnyAsync(cb => cb.Id == request.ClinicBranchId, cancellationToken);
        
        if (!clinicBranchExists)
        {
            return Result<Guid>.Fail(MessageCodes.Common.CLINIC_BRANCH_NOT_FOUND);
        }

        // Check if medical supply with same name already exists in this clinic branch
        var existingSupply = await _context.MedicalSupplies
            .AsNoTracking()
            .FirstOrDefaultAsync(s => s.Name.ToLower() == request.Name.ToLower() && s.ClinicBranchId == request.ClinicBranchId, cancellationToken);
        
        if (existingSupply != null)
        {
            return Result<Guid>.FailField("name", MessageCodes.MedicalSupply.ALREADY_EXISTS);
        }

        var supply = new MedicalSupply
        {
            // ID will be generated by database
            ClinicBranchId = request.ClinicBranchId,
            Name = request.Name,
            UnitPrice = request.UnitPrice,
            QuantityInStock = request.QuantityInStock,
            MinimumStockLevel = request.MinimumStockLevel
        };

        _context.MedicalSupplies.Add(supply);
        await _context.SaveChangesAsync(cancellationToken);

        return Result<Guid>.Ok(supply.Id);
    }
}