using ClinicManagement.Application.Features.Patients.Commands;
using ClinicManagement.Domain.Enums;
using static ClinicManagement.Domain.Enums.BloodTypeExtensions;
using FsCheck;
using FsCheck.Xunit;

namespace ClinicManagement.Application.Tests.Patients;

public class CreatePatientCommandHandlerTests
{
    private static readonly Dictionary<string, BloodType> KnownMappings = new()
    {
        ["A+"]  = BloodType.APositive,
        ["A-"]  = BloodType.ANegative,
        ["B+"]  = BloodType.BPositive,
        ["B-"]  = BloodType.BNegative,
        ["AB+"] = BloodType.ABPositive,
        ["AB-"] = BloodType.ABNegative,
        ["O+"]  = BloodType.OPositive,
        ["O-"]  = BloodType.ONegative,
    };

    [Property]
    public Property ParseBloodType_KnownStrings_ReturnCorrectEnum()
    {
        return Prop.ForAll(
            Gen.Elements(KnownMappings.Keys.ToArray()).ToArbitrary(),
            input => ParseBloodType(input) == KnownMappings[input]
        );
    }

    [Property]
    public Property ParseBloodType_UnknownStrings_ReturnNull()
    {
        var knownStrings = new HashSet<string>(KnownMappings.Keys);
        return Prop.ForAll(
            Arb.Default.String().Filter(s => s != null && !knownStrings.Contains(s)),
            input => ParseBloodType(input) == null
        );
    }

    // PatientCode is now generated by PatientCounterRepository (sequential per clinic).
    // Format: zero-padded 7 digits — "0000001", "0000002", ...
    [Theory]
    [InlineData(1,       "0000001")]
    [InlineData(42,      "0000042")]
    [InlineData(9999999, "9999999")]
    public void PatientCode_Format_IsZeroPadded7Digits(int counter, string expected)
    {
        var code = counter.ToString("D7");
        Assert.Equal(expected, code);
        Assert.Equal(7, code.Length);
        Assert.True(code.All(char.IsDigit));
    }
}
