using ClinicManagement.Application.Abstractions.Data;
using ClinicManagement.Application.Features.Patients.Commands;
using ClinicManagement.Application.Tests.Common;
using ClinicManagement.Domain.Common.Constants;
using FluentAssertions;

namespace ClinicManagement.Application.Tests.Patients;

/// <summary>
/// Tests for CreatePatientCommandHandler.
/// Blood type parsing and patient code formatting are tested here as they are
/// pure logic embedded in the handler and its helpers.
/// </summary>
public class CreatePatientCommandHandlerTests
{
    // PatientCode is generated by PatientCounterRepository (sequential per clinic).
    // Format: zero-padded 4 digits — "0001", "0002", ...
    [Theory]
    [InlineData(1,    "0001")]
    [InlineData(42,   "0042")]
    [InlineData(9999, "9999")]
    public void PatientCode_Format_IsZeroPadded4Digits(int counter, string expected)
    {
        var code = counter.ToString("D4");
        Assert.Equal(expected, code);
        Assert.Equal(4, code.Length);
        Assert.True(code.All(char.IsDigit));
    }
}
