### Login and set token variable
# @name login
POST {{baseUrl}}/api/auth/login
Content-Type: application/json

{
  "emailOrUsername": "user@example.com",
  "password": "string"
}

@token = {{login.response.body.$.token}}

### Get all chronic diseases
GET {{baseUrl}}/api/chronic-diseases
Authorization: Bearer {{token}}

