using ClinicManagement.Application.Common.Interfaces;
using ClinicManagement.Application.Common.Models;
using ClinicManagement.Domain.Common.Constants;
using ClinicManagement.Domain.Common.Interfaces;
using ClinicManagement.Domain.Entities;
using FluentValidation;
using MediatR;
using Microsoft.EntityFrameworkCore;

namespace ClinicManagement.Application.Features.MedicalServices.Commands.CreateMedicalService;

public record CreateMedicalServiceCommand : IRequest<Result<Guid>>
{
    public Guid ClinicBranchId { get; init; }
    public string Name { get; init; } = null!;
    public decimal DefaultPrice { get; init; }
    public bool IsOperation { get; init; }
}


public class CreateMedicalServiceCommandHandler : IRequestHandler<CreateMedicalServiceCommand, Result<Guid>>
{
    private readonly IUnitOfWork _unitOfWork;

    public CreateMedicalServiceCommandHandler(IUnitOfWork unitOfWork)
    {
        _unitOfWork = unitOfWork;
    }

    public async Task<Result<Guid>> Handle(CreateMedicalServiceCommand request, CancellationToken cancellationToken)
    {
        // Check if clinic branch exists
        var clinicBranchExists = await _unitOfWork.Repository<ClinicBranch>()
            .AnyAsync(cb => cb.Id == request.ClinicBranchId, cancellationToken);
        
        if (!clinicBranchExists)
        {
            return Result<Guid>.FailSystem("NOT_FOUND", "Clinic branch not found");
        }

        // Check if medical service with same name already exists in this clinic branch
        var existingService = await _unitOfWork.MedicalServices
            .GetByNameAndClinicBranchAsync(request.Name, request.ClinicBranchId, cancellationToken);
        
        if (existingService != null)
        {
            return Result<Guid>.FailValidation("name", "A medical service with this name already exists in this clinic branch");
        }

        var service = new MedicalService
        {
            // ID will be generated by database
            ClinicBranchId = request.ClinicBranchId,
            Name = request.Name,
            DefaultPrice = request.DefaultPrice,
            IsOperation = request.IsOperation
        };

        await _unitOfWork.MedicalServices.AddAsync(service, cancellationToken);
        await _unitOfWork.SaveChangesAsync(cancellationToken);

        return Result<Guid>.Ok(service.Id);
    }
}