using ClinicManagement.Application.Common.Interfaces;
using ClinicManagement.Application.Common.Models;
using ClinicManagement.Domain.Common.Constants;
using ClinicManagement.Domain.Entities;
using FluentValidation;
using MediatR;
using Microsoft.EntityFrameworkCore;

namespace ClinicManagement.Application.Features.MedicalServices.Commands.CreateMedicalService;

public record CreateMedicalServiceCommand : IRequest<Result<Guid>>
{
    public Guid ClinicBranchId { get; init; }
    public string Name { get; init; } = null!;
    public decimal DefaultPrice { get; init; }
    public bool IsOperation { get; init; }
}


public class CreateMedicalServiceCommandHandler : IRequestHandler<CreateMedicalServiceCommand, Result<Guid>>
{
    private readonly IApplicationDbContext _context;

    public CreateMedicalServiceCommandHandler(IApplicationDbContext context)
    {
        _context = context;
    }

    public async Task<Result<Guid>> Handle(CreateMedicalServiceCommand request, CancellationToken cancellationToken)
    {
        // Check if clinic branch exists
        var clinicBranchExists = await _context.ClinicBranches
            .AnyAsync(cb => cb.Id == request.ClinicBranchId, cancellationToken);
        
        if (!clinicBranchExists)
        {
            return Result<Guid>.Fail(MessageCodes.Common.CLINIC_BRANCH_NOT_FOUND);
        }

        // Check if medical service with same name already exists in this clinic branch
        var existingService = await _context.MedicalServices
            .AsNoTracking()
            .FirstOrDefaultAsync(s => s.Name.ToLower() == request.Name.ToLower() && s.ClinicBranchId == request.ClinicBranchId, cancellationToken);
        
        if (existingService != null)
        {
            return Result<Guid>.FailField("name", MessageCodes.MedicalService.ALREADY_EXISTS);
        }

        var service = new MedicalService
        {
            // ID will be generated by database
            ClinicBranchId = request.ClinicBranchId,
            Name = request.Name,
            DefaultPrice = request.DefaultPrice,
            IsOperation = request.IsOperation
        };

        _context.MedicalServices.Add(service);
        await _context.SaveChangesAsync(cancellationToken);

        return Result<Guid>.Ok(service.Id);
    }
}