using ClinicManagement.Application.Common.Interfaces;
using ClinicManagement.Application.Common.Models;
using ClinicManagement.Domain.Common.Constants;
using ClinicManagement.Domain.Common.Enums;
using ClinicManagement.Domain.Common.Interfaces;
using ClinicManagement.Domain.Entities;
using FluentValidation;
using MediatR;
using Microsoft.EntityFrameworkCore;

namespace ClinicManagement.Application.Features.Payments.Commands.CreatePayment;

public record CreatePaymentCommand : IRequest<Result<Guid>>
{
    public Guid InvoiceId { get; init; }
    public decimal Amount { get; init; }
    public DateTime PaymentDate { get; init; }
    public PaymentMethod PaymentMethod { get; init; }
    public string? Note { get; init; }
    public string? ReferenceNumber { get; init; }
}


public class CreatePaymentCommandHandler : IRequestHandler<CreatePaymentCommand, Result<Guid>>
{
    private readonly IUnitOfWork _unitOfWork;

    public CreatePaymentCommandHandler(IUnitOfWork unitOfWork)
    {
        _unitOfWork = unitOfWork;
    }

    public async Task<Result<Guid>> Handle(CreatePaymentCommand request, CancellationToken cancellationToken)
    {
        // Validate invoice exists
        var invoice = await _unitOfWork.Invoices.GetByIdAsync(request.InvoiceId, cancellationToken);
        if (invoice == null)
        {
            return Result<Guid>.FailSystem("NOT_FOUND", "Invoice not found");
        }

        // Check if payment amount doesn't exceed remaining amount
        var totalPaid = await _unitOfWork.Payments.GetTotalPaidByInvoiceAsync(request.InvoiceId, cancellationToken);
        
        var remainingAmount = invoice.FinalAmount - totalPaid;
        
        if (request.Amount > remainingAmount)
        {
            return Result<Guid>.FailValidation("amount", $"Payment amount cannot exceed remaining amount of {remainingAmount:C}");
        }

        var payment = new Payment
        {
            // ID will be generated by database
            InvoiceId = request.InvoiceId,
            Amount = request.Amount,
            PaymentDate = request.PaymentDate,
            PaymentMethod = request.PaymentMethod,
            Note = request.Note,
            ReferenceNumber = request.ReferenceNumber
        };

        await _unitOfWork.Payments.AddAsync(payment, cancellationToken);
        await _unitOfWork.SaveChangesAsync(cancellationToken);

        return Result<Guid>.Ok(payment.Id);
    }
}