using ClinicManagement.Application.Common.Interfaces;
using ClinicManagement.Application.Common.Models;
using ClinicManagement.Domain.Common.Constants;
using ClinicManagement.Domain.Common.Enums;
using ClinicManagement.Domain.Entities;
using FluentValidation;
using MediatR;
using Microsoft.EntityFrameworkCore;

namespace ClinicManagement.Application.Features.Payments.Commands.CreatePayment;

public record CreatePaymentCommand : IRequest<Result<Guid>>
{
    public Guid InvoiceId { get; init; }
    public decimal Amount { get; init; }
    public DateTime PaymentDate { get; init; }
    public PaymentMethod PaymentMethod { get; init; }
    public string? Note { get; init; }
    public string? ReferenceNumber { get; init; }
}


public class CreatePaymentCommandHandler : IRequestHandler<CreatePaymentCommand, Result<Guid>>
{
    private readonly IApplicationDbContext _context;

    public CreatePaymentCommandHandler(IApplicationDbContext context)
    {
        _context = context;
    }

    public async Task<Result<Guid>> Handle(CreatePaymentCommand request, CancellationToken cancellationToken)
    {
        // Validate invoice exists
        var invoice = await _context.Invoices.FindAsync(new object[] { request.InvoiceId }, cancellationToken);
        if (invoice == null)
        {
            return Result<Guid>.Fail(MessageCodes.Invoice.NOT_FOUND);
        }

        // Check if payment amount doesn't exceed remaining amount
        var totalPaid = await _context.Payments
            .AsNoTracking()
            .Where(p => p.InvoiceId == request.InvoiceId)
            .SumAsync(p => p.Amount, cancellationToken);
        
        var remainingAmount = invoice.FinalAmount - totalPaid;
        
        if (request.Amount > remainingAmount)
        {
            return Result<Guid>.FailField("amount", MessageCodes.Payment.AMOUNT_EXCEEDS_REMAINING);
        }

        var payment = new Payment
        {
            // ID will be generated by database
            InvoiceId = request.InvoiceId,
            Amount = request.Amount,
            PaymentDate = request.PaymentDate,
            PaymentMethod = request.PaymentMethod,
            Note = request.Note,
            ReferenceNumber = request.ReferenceNumber
        };

        _context.Payments.Add(payment);
        await _context.SaveChangesAsync(cancellationToken);

        return Result<Guid>.Ok(payment.Id);
    }
}