name: Build, publish and deploy to MonsterASP.NET

on:
  push:
    branches: [ main ] # Only triggers when you push to the main branch

jobs:
  build_and_deploy:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET 10
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0
          
      - name: Install dependencies
        run: dotnet restore ClinicManagement.slnx
        
      - name: Build
        run: dotnet build ClinicManagement.slnx --configuration Release --no-restore

      - name: Install SQL Server LocalDB
        uses: potatoqualitee/mssqlsuite@v1.11
        with:
          install: localdb

      - name: Test with .NET
        run: dotnet test ClinicManagement.slnx --no-build --configuration Release --verbosity normal

      - name: Publish
        # Targets the specific API project in your src folder
        run: dotnet publish src/ClinicManagement.API/ClinicManagement.API.csproj --configuration Release --output ./publish --runtime win-x64 --self-contained true
        
      - name: Deploy to MonsterASP.NET via WebDeploy
        uses: rasmusbuchholdt/simply-web-deploy@2.1.0
        with:
          website-name: ${{ secrets.WEBSITE_NAME }}
          server-computer-name: ${{ secrets.SERVER_COMPUTER_NAME }}
          server-username: ${{ secrets.SERVER_USERNAME }}
          server-password: ${{ secrets.SERVER_PASSWORD }}
          source-path: ./publish # Ensures it deploys the files from the publish folder
